switch Microsoft OpenJDK to use static URL's
actions/setup-java pull request #301
Opened 2022-03-16 13:47 UTC by gdams

fixes: https://github.com/actions/setup-java/issues/296

**Description:**
Describe your changes.

**Related issue:**
Add link to the related issue.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-03-24 08:37 UTC, joschi commented
@gdams Referring to this code comment:
> We will need Microsoft to add an endpoint where we can query for versions.

Is there any URL which can be used to retrieve metadata about (all) the Microsoft OpenJDK builds, maybe even an API similar to the [Adoptium API](https://api.adoptium.net/q/swagger-ui/)?

2022-03-26 00:41 UTC, brunoborges commented
@joschi we don't have that ready yet.

2022-03-26 00:42 UTC, brunoborges requested changes

2022-03-26 00:42 UTC, brunoborges commented on dist/setup/index.js
>              // M1 is only supported for Java 16 & 17
@gdams we now provide JDK 11 for M1 as well. I think this block can be simplified.

2022-03-28 15:11 UTC, dmitry-shibanov commented
Hello @gdams. Could you please run these `npm run build && npm run format` commands.

2022-04-11 08:18 UTC, dmitry-shibanov commented
Hello @gdams, just a gentle ping.

2022-06-16 03:57 UTC, Skiba36 approved these changes

2022-06-20 15:23 UTC, karianna commented
@gdams - needs a rebase

2022-10-03 09:25 UTC, dmitry-shibanov commented
Hello everyone. I'm going to close the pull request because we added manifest with versions for Microsoft OpenJDK. Now we can add new versions to the manifest file without releasing new version of the action.

2022-10-03 09:25 UTC, closed without merging